accounts/urls.py
from django.urls import path
from accounts import views as accounts




app_name = 'accounts'
urlpatterns = [
   path('', accounts.login_page, name="login_page"),


   path('register/', accounts.register_page, name="register_page"),
   path('register/success', accounts.registration_success, name="register_success"),
   path('activation/success', accounts.activation_success, name="activation_success"),


   path('logout/', accounts.logout_process, name="logout_process"),


   path('change_password/', accounts.change_password, name="change_password"),
   path('activate/<str:uidb64>/<str:token>/', accounts.activate_user, name='activate_user'),
   
   path('profile/', accounts.list_profile, name='list_profile'),
   path('profile/update/', accounts.update_profile, name='update_profile'),


  






]

dashboard/urls.py
from django.urls import path
from dashboard import views as dashboard




app_name = 'dashboard'
urlpatterns = [
  path('dashboard/', dashboard.dashboard_page, name="dashboard_page"),




  path('addemployee/', dashboard.add_employee, name="add_employee"),
  path('employees/', dashboard.list_employee, name="list_employee"),
  path('employee/update/<int:id>', dashboard.update_employee, name="update_employee"),
  path('employee/delete/<int:id>', dashboard.delete_employee, name="delete_employee"),




  path('medicine/', dashboard.medicine_list_admin, name="medicine_list_admin"),
  path('medicine/delete/<int:id>', dashboard.delete_medicine, name="delete_medicine"),
  path('medicine/update/<int:id>', dashboard.update_medicine, name="update_medicine"),
  path('medicine/add/', dashboard.add_medicine, name="add_medicine"),




  path('faq/', dashboard.faq_list, name="faq_list"),
  path('faq/add/', dashboard.faq_add, name="faq_add"),




  path('upload/prescription/', dashboard.upload_prescription, name="upload_prescription"),
  path('prescription/<int:id>/update', dashboard.update_prescription, name="update_prescription"),
  path('prescription/', dashboard.presciption_list_admin, name="presciption_list_admin"),
 
  path('notification/add/', dashboard.add_notification, name="add_notification"),
 
  path('sales/', dashboard.sales_list, name="sales_list"),
  path('sales/add/', dashboard.add_sales, name="add_sales"),
  path('sales/<int:id>/update/', dashboard.update_sales, name="update_sales"),
 
  path("bills/", dashboard.list_bill, name="list_bill"),
  path("bills/add/", dashboard.generate_bill, name="generate_bill"),
  path("bills/update/<int:id>/", dashboard.update_bill, name="update_bill"),


  path("billitem/<int:bill_id>/", dashboard.bill_item_list, name="bill_item_list"),
  path("billitem/<int:bill_id>/add/", dashboard.generate_bill_items, name="generate_bill_items"),
  path("billitem/<int:bill_id>/delete/<int:item_id>/", dashboard.delete_bill_item, name="delete_bill_item"),


  path("cbills/<int:app_id>", dashboard.customer_bills, name="customer_bills"),
 
  path("search/", dashboard.search_by_email, name="search_by_email"),
]

pharmaLink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


admin.site.site_header = "pharmaLink"
admin.site.index_title = "pharmaLink dashboard"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('dashboard.urls')),


    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Dashboard</title>


   <!-- Google Font: Source Sans Pro -->
   <link rel="stylesheet"
       href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
   <!-- Font Awesome -->
   <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
   <!-- Ionicons -->
   <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
   <!-- Tempusdominus Bootstrap 4 -->
   <link rel="stylesheet"
       href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
   <!-- iCheck -->
   <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
   <!-- JQVMap -->
   <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
   <!-- Theme style -->
   <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
   <!-- overlayScrollbars -->
   <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
   <!-- Daterange picker -->
   <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
   <!-- summernote -->
   <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">


   {% block css %}{% endblock css %}
</head>


<body class="hold-transition sidebar-mini layout-fixed">
   <div class="wrapper">
      


       <!-- Navbar -->
       {% block Navbar %}{% endblock Navbar %}
       <!-- /.navbar -->
      
      
       <!-- Main Sidebar Container -->
       {% block sidebar %}{% endblock sidebar %}
               <!-- main containent here  -->
       <div class="content-wrapper">     
           <section class = "content">
          
       {% if messages %}
       {% for message in messages  %}
       <div class="alert alert-info text-center" role="alert">
           {{message}}
         </div>
       {% endfor %}
       {% endif %}
               {% block content %}{% endblock content %}   
           </section>
       </div>
       <aside class="control-sidebar control-sidebar-dark">
       </aside>
   </div>
   {% block script %}{% endblock script %}
</body>


</html>

templates/partials/navbar.html
{% load static %}




<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <!-- <ul class="navbar-nav">
      <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
  </ul> -->




  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
       <li class="nav-item">
          <a class="nav-link" data-widget="navbar-search" href="#" role="button">
              <i class="fas fa-search"></i>
          </a>
          <div class="navbar-search-block">
              <form class="form-inline" action='{% url "dashboard:search_by_email" %}' method='get'>
               {% csrf_token %}
                  <div class="input-group input-group-sm">
                      <input class="form-control form-control-navbar" name='email' type="search" placeholder="Search invoice"
                          aria-label="Search">
                      <div class="input-group-append">
                          <button class="btn btn-navbar" type="submit">
                              <i class="fas fa-search"></i>
                          </button>
                          <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                              <i class="fas fa-times"></i>
                          </button>
                      </div>
                  </div>
              </form>
          </div>
      </li>   
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown show">
          <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="true">
              <i class="far fa-comments"></i>
              <span class="badge badge-danger navbar-badge">{{count}}</span>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right show" style="left: inherit; right: 0px;">
            <a href="#" class="dropdown-item">
              <!-- Message Start -->
              {% if notification %}
              {% for i in notification %}
              {% if request.user == i.specific_user %}
              <div class="media">
                <div class="media-body">
                  <h3 class="dropdown-item-title">
                    {{i.created_by.get_full_name}}
                  </h3>
                  <p class="text-sm">{{i.notification}}</p>
                  <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i>{{i.created_date}}</p>
                </div>
              </div>
              {% endif %}
              {% endfor %}
              {% endif %}
              <!-- Message End -->
            </a>
            <div class="dropdown-divider"></div>
            {% comment %} <a href="#" class="dropdown-item dropdown-footer">See All Messages</a> {% endcomment %}
          </div>
        </li>




      <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
              <i class="fas fa-bars"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
              <div class="dropdown-divider"></div>
              <a href="{% url "accounts:list_profile" %}" class="dropdown-item">
                  <i class="fas fa-user mr-2"></i> Profile
              </a>
              <a href="{% url "accounts:change_password" %}" class="dropdown-item">
                  <i class="fas fa-eye mr-2"></i> Change Passowrd
              </a>
              <a href="{% url "accounts:logout_process" %}" class="dropdown-item">
                  <i class="fas fa-sign-out-alt mr-2"></i> Logout
              </a>
              <div class="dropdown-divider"></div>
          </div>
      </li>
  </ul>
</nav>

templates/partials/script.html
{% load static %}


<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
   <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
   <script>
       $.widget.bridge('uibutton', $.ui.button)
   </script>
   <!-- Bootstrap 4 -->
   <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
   <!-- ChartJS -->
   <script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
   <!-- Sparkline -->
   <script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
   <!-- JQVMap -->
   <script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
   <script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
   <!-- jQuery Knob Chart -->
   <script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
   <!-- daterangepicker -->
   <script src="{% static 'plugins/moment/moment.min.js' %}"></script>
   <script src="{% static 'adminlte/plugins/daterangepicker/daterangepicker.js' %}"></script>
   <!-- Tempusdominus Bootstrap 4 -->
   <script
       src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
   <!-- Summernote -->
   <script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
   <!-- overlayScrollbars -->
   <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
   <!-- AdminLTE App -->
   <script src="{% static 'dist/js/adminlte.js' %}"></script>
   <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
   <script src="{% static 'dist/js/pages/dashboard.js' %}"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>


   <script>
       $(document).ready(function(){
           $('.datepicker').datepicker({
               format: 'yyyy-mm-dd',
               autoclose:true,
               todayHighlight: true,
           });
       });
   </script>

templates/partials/sidebar.html
{% load static %}








<aside class="main-sidebar sidebar-dark-primary elevation-4">
 <!-- Brand Logo -->
 <a href="{% url "dashboard:dashboard_page" %}" class="brand-link">
     <img src="{% static 'dist/img/R.jpg' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
         style="opacity: .8">
     <span class="brand-text font-weight-light">pharmaLink</span>
 </a>








 <!-- Sidebar -->
 <div class="sidebar">
     <!-- Sidebar user panel (optional) -->
     <div class="user-panel mt-3 pb-3 mb-3 d-flex">
         <div class="image">
             <img src="{% static 'dist/img/123.jpg' %}" class="img-circle elevation-2" alt="User Image">
         </div>
         <div class="info">
             <a href="#" class="d-block">{{request.user.get_full_name}}</a>
         </div>
     </div>
     <nav class="mt-2">
         <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
             data-accordion="false">
             <li class="nav-item">
                 <a href="{% url "dashboard:dashboard_page" %}" class="nav-link">
                     <i class="nav-icon fas fa-home mr-2"></i>
                     <p>
                         DashBoard
                     </p>
                 </a>
             </li>
             {% if request.user.is_superuser %}
             <li class="nav-item">
                 <a href="#" class="nav-link">
                     <i class="nav-icon fas fa-user mr-2"></i>








                     <p>
                         Employee
                         <i class="fas fa-angle-left right"></i>
                     </p>
                 </a>
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:add_employee" %}" class="nav-link">
                             <i class=" fas fa-plus nav-icon"></i>








                             <p>Add Employee</p>
                         </a>
                     </li>
                 </ul>
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:list_employee" %}" class="nav-link">
                             <i class=" fas fa-eye nav-icon"></i>








                             <p>View Employee</p>
                         </a>
                     </li>
                 </ul>
             </li>
             {% endif %}
             {% if not request.user.is_customer %}
             <li class="nav-item">
                 <a href="#" class="nav-link">
                     <i class="nav-icon fas fa-user mr-2"></i>








                     <p>
                         Stocks
                         <i class="fas fa-angle-left right"></i>
                     </p>
                 </a>
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:add_medicine" %}" class="nav-link">
                             <i class=" fas fa-plus nav-icon"></i>
                             <p>Add Stock</p>
                         </a>
                     </li>
                 </ul>
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:medicine_list_admin" %}" class="nav-link">
                             <i class=" fas fa-eye nav-icon"></i>
                             <p>View Stocks</p>
                         </a>
                     </li>
                 </ul>
             </li>
             {% endif %}
             {% if request.user.is_customer or request.user.is_employee or request.user.is_superuser%}
             <li class="nav-item">
                 <a href="#" class="nav-link">
                     <i class="nav-icon fas fa-prescription-bottle-alt mr-2"></i>
                     <p>
                         prescription
                         <i class="fas fa-angle-left right"></i>
                     </p>
                 </a>
                 {% if request.user.is_customer or request.user.is_employee %}
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:upload_prescription" %}" class="nav-link">
                             <i class=" fas fa-prescription-bottle-alt nav-icon"></i>
                             <p>Add prescription</p>
                         </a>
                     </li>
                 </ul>
                 {% endif %}
                 {% if request.user.is_employee or request.user.is_superuser %}
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:presciption_list_admin" %}" class="nav-link">
                             <i class=" fas fa-eye nav-icon"></i>
                             <p>View prescription</p>
                         </a>
                     </li>
                 </ul>
                 {% endif %}
             </li>
             {% endif %}
             {% if not request.user.is_customer %}
             <li class="nav-item">
                 <a href="#" class="nav-link">
                     <i class="nav-icon fas fa-user mr-2"></i>
                     <p>
                         FAQ
                         <i class="fas fa-angle-left right"></i>
                     </p>
                 </a>
                
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:faq_list" %}" class="nav-link">
                             <i class=" fas fa-plus nav-icon"></i>
                             <p>View FAQ</p>
                         </a>
                     </li>
                 </ul>
                 {% if request.user.is_superuser  or request.user.is_employee %}
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:faq_add" %}    " class="nav-link">
                             <i class=" fas fa-eye nav-icon"></i>
                             <p>Add FAQ</p>
                         </a>
                     </li>
                 </ul>
                 {% endif %}
             </li>
           {% endif %}
             {% if request.user.is_employee or request.user.is_superuser %}
              <li class="nav-item">
                  <a href="{% url "dashboard:add_notification" %}" class="nav-link">
                      <i class="nav-icon fas fa-prescription-bottle-alt mr-2"></i>
                      <p>
                          Add Notification
                          <i class="fas fa-angle-right right"></i>
                      </p>
                  </a>
              </li>
              {% endif %}
              {% if not request.user.is_customer %}
             <li class="nav-item">
                 <a href="#" class="nav-link">
                     <i class="nav-icon fas fa-user mr-2"></i>
                     <p>
                         Sales
                         <i class="fas fa-angle-left right"></i>
                     </p>
                 </a>
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:add_sales" %}" class="nav-link">
                             <i class=" fas fa-plus nav-icon"></i>
                             <p>Add sales</p>
                         </a>
                     </li>
                 </ul>
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:sales_list" %}" class="nav-link">
                             <i class=" fas fa-eye nav-icon"></i>
                             <p>View Sales</p>
                         </a>
                     </li>
                 </ul>
             </li>
             {% endif %}
             {% if request.user.is_superuser or request.user.is_employee %}
             <li class="nav-item">
                 <a href="#" class="nav-link">
                     <i class="nav-icon fas fa-user mr-2"></i>


                     <p>
                         Bills
                         <i class="fas fa-angle-left right"></i>
                     </p>
                 </a>
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:generate_bill" %}" class="nav-link">
                             <i class=" fas fa-plus nav-icon"></i>
                             <p>Create Bills</p>
                         </a>
                     </li>
                 </ul>
                 <ul class="nav nav-treeview">
                     <li class="nav-item">
                         <a href="{% url "dashboard:list_bill" %}" class="nav-link">
                             <i class=" fas fa-eye nav-icon"></i>
                             <p>Bills</p>
                         </a>
                     </li>
                 </ul>
             </li>
             {% endif %}
         </ul>
     </nav>
     <!-- /.sidebar-menu -->
 </div>
 <!-- /.sidebar -->
</aside>