accounts/urls.py
from django.urls import path
from accounts import views as accounts




app_name = 'accounts'
urlpatterns = [
   path('', accounts.login_page, name="login_page"),


   path('register/', accounts.register_page, name="register_page"),
   path('register/success', accounts.registration_success, name="register_success"),
   path('activation/success', accounts.activation_success, name="activation_success"),


   path('logout/', accounts.logout_process, name="logout_process"),


   path('change_password/', accounts.change_password, name="change_password"),
   path('activate/<str:uidb64>/<str:token>/', accounts.activate_user, name='activate_user'),
   
   path('profile/', accounts.list_profile, name='list_profile'),
   path('profile/update/', accounts.update_profile, name='update_profile'),


  






]

pharmaLink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


admin.site.site_header = "pharmaLink"
admin.site.index_title = "pharmaLink dashboard"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('dashboard.urls')),


    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser           
# Create your models here.


class User(AbstractUser):
   email = models.EmailField(unique=True, verbose_name = 'email')
   is_employee = models.BooleanField(default=False)
   is_customer = models.BooleanField(default=False)
   phone = models.CharField(max_length=255, null=True, blank=True)
   address = models.CharField(max_length=255, null=True, blank=True)
   dob = models.DateField(null=True, blank=True)
   profile_pic = models.ImageField(upload_to='profile', default='profile/user.jpg')
  


  
   USERNAME_FIELD = "email"
   REQUIRED_FIELDS = "username","first_name","last_name"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User
from django.contrib.auth.forms import PasswordChangeForm




class UserRegisterForm(UserCreationForm):
   class Meta:
       model = User
       fields = ('email', 'password1', 'password2', 'first_name', 'last_name')


class CustomPasswordChangeForm(PasswordChangeForm):
   pass






class updateProfile(forms.ModelForm):
   dob = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))
   class Meta:
       model = User
       fields = ('first_name','last_name','address','phone','profile_pic','dob')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from accounts.models import User
from accounts.forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.forms import CustomPasswordChangeForm
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.conf import settings
from django.http import Http404
from django.utils.http import urlsafe_base64_decode
from accounts.forms import *


from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required


# Create your views here.
def login_page(request):
   if request.user.is_authenticated:
       return redirect ('dashboard:dashboard_page')


   if request.method=='POST':
       email = request.POST.get('email')
       password = request.POST.get('password')
       user = authenticate(request = request, email = email, password = password)#authenticating User
       if user is not None:
           login(request = request, user = user)
           return redirect ('dashboard:dashboard_page')
       else:
           messages.error(request, "Invalid Details")
           return redirect('accounts:login_page')
   return render(request,"accounts/login.html")


def registration_success(request):
   return render(request, 'accounts/registration/registration_success.html')


def activation_success(request):
   return render(request, 'accounts/registration/activation_success.html')


def register_page(request):
   context = {}
   if request.user.is_authenticated:
       return redirect('dashboard:dashboard_page')
  
   if request.method == 'POST':
       form = UserRegisterForm(request.POST)
       if form.is_valid():
           user = form.save(commit = False)
           user.is_customer=True
           user.is_active = False
           user.username = form.cleaned_data.get('email')
           user.save()


           #creating activation link
           uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
           token = default_token_generator.make_token(user)
           activation_link = f"http://localhost:8000/activate/{uidb64}/{token}"
           #composing mail
           subject_message = "Verify Account"
           message = render_to_string(
               "accounts/registration/activation_email.html",
               {
                   "activation_link" : activation_link,
                   "user" : user,
               },


           )
           #send mail
           email = EmailMessage(subject_message, message, settings.DEFAULT_FROM_EMAIL, [user.email])
           email.content_subtype = "html"
           email.send(fail_silently= False)
           messages.success(request, 'successfully registered')
           return redirect('accounts:register_success')
       print(form.errors, ".............")
   else:
       form = UserRegisterForm()
   context = {
       'form' : form,
   }
   return render(request, 'accounts/register.html', context)


"user activation"
def activate_user(request, uidb64, token):
  try:
      uid = str(urlsafe_base64_decode(uidb64), 'utf-8')
      user = User.objects.get(id=uid)




      if user and default_token_generator.check_token(user, token):
          user.is_active = True
          user.save()
          return redirect('accounts:activation_success')
  except User.DoesNotExist:
      raise Http404("User not found or token is invalid.")
  except Exception as e:
      print(str(e))




  return render(request, 'accounts/registration/activation_failure.html')


"""logout view"""
@login_required(login_url = '/')
def logout_process(request):
   logout(request)
   return redirect('accounts:login_page')


@login_required(login_url= '/')
def change_password(request):
   if request.method == "POST":
       form = CustomPasswordChangeForm(request.user, request.POST)
       if form.is_valid():
           user = form.save()
           messages.success(request, 'Your password was successfully updated!')
           return redirect('dashboard:dashboard_page')
   else:
       form = CustomPasswordChangeForm(request.user)
   return render(request, "accounts/change_password.html", {"form" : form})










@login_required(login_url='/')
def update_profile(request):
   instance = request.user
   if request.method == 'POST':
       form = updateProfile(request.POST, request.FILES, instance=instance)
       if form.is_valid():
           form.save()
           messages.success(request, "Successfully updated profile")
           return redirect('accounts:list_profile')
   else:
       form = updateProfile(instance=instance)
   return render(request, 'accounts/profile/update.html', {"form": form})


  
      




@login_required(login_url='/')
def list_profile(request):
   profile = request.user
   return render(request, 'accounts/profile/list.html', {"profile":profile})

templates/accounts/profile/list.html
{% extends "partials/layout.html" %}


{% block Navbar %}
{% include "partials/navbar.html" %}
{% endblock Navbar %}


{% block sidebar %}
{% include "partials/sidebar.html" %}
{% endblock sidebar %}


{% block content %}
<div class="container">
   <div class="col-md-12 pt-5">


       <!-- Profile Image -->
       <div class="card  card-outline">
         <div class="card-body box-profile">
           <div class="text-center">
               {% if profile.profile_pic.url %}
                   <img class="profile-user-img img-fluid img-circle" src="{{profile.profile_pic.url}}" alt="User profile picture">
               {% endif %}
           </div>


           <h3 class="profile-username text-center">{{profile.get_full_name}}</h3>


           <p class="text-muted text-center">{{profile.email}}</p>


           <ul class="list-group list-group-unbordered mb-3">
             <li class="list-group-item">
               <b>user status</b>
               {% if request.user.is_customer %}
                   <a class="float-right badge bg-primary">Customer</a>
               {% endif %}
               {% if request.user.is_employee %}
                   <a class="float-right badge bg-primary">Employee</a>
               {% endif %}
               {% if request.user.is_superuser %}
                   <a class="float-right badge bg-primary">Admin</a>
               {% endif %}
             </li>
             <li class="list-group-item">
               <b>Email</b> <a class="float-right">{{profile.email}}</a>
             </li>
             <li class="list-group-item">
               <b>Username</b> <a class="float-right">{{profile.username}}</a>
             </li> <li class="list-group-item">
               <b>Date Of Birth</b> <a class="float-right">{{profile.dob}}</a>
             </li>
             <li class="list-group-item">
               <b>Contact number</b> <a class="float-right">{{profile.phone}}</a>
             </li>
             <li class="list-group-item">
               <b>Address</b> <a class="float-right">{{profile.address}}</a>
             </li>
           </ul>


           <a href="{% url "accounts:update_profile" %}" class="btn btn-primary btn-block"><b>Update</b></a>
         </div>
         <!-- /.card-body -->
       </div>
       <!-- /.card -->
     </div>
</div>
{% endblock content %}


{% block script %}  
{% include "partials/script.html" %}
{% endblock script %}

templates/accounts/profile/update.html
{% extends "partials/layout.html" %}


{% block Navbar %}
{% include "partials/navbar.html" %}
{% endblock Navbar %}


{% block sidebar %}
{% include "partials/sidebar.html" %}
{% endblock sidebar %}


{% block content %}
{% load crispy_forms_tags %}
<h1 class="p-2 text-mute text-center">Update Profile</h1>
<div class="container">
   <form action="" method="post" enctype="multipart/form-data">
       {% csrf_token %}
       {{form|crispy}}
       <button class="btn btn-info">Update Profile</button>
   </form>
</div>
{% endblock content %}


{% block script %}  
{% include "partials/script.html" %}
{% endblock script %}