accounts/urls.py
from django.urls import path
from accounts import views as accounts




app_name = 'accounts'
urlpatterns = [
   path('', accounts.login_page, name="login_page"),


   path('register/', accounts.register_page, name="register_page"),
   path('register/success', accounts.registration_success, name="register_success"),
   path('activation/success', accounts.activation_success, name="activation_success"),


   path('logout/', accounts.logout_process, name="logout_process"),


   path('change_password/', accounts.change_password, name="change_password"),
   path('activate/<str:uidb64>/<str:token>/', accounts.activate_user, name='activate_user'),
   
   path('profile/', accounts.list_profile, name='list_profile'),
   path('profile/update/', accounts.update_profile, name='update_profile'),


  






]

dashboard/urls.py
from django.urls import path
from dashboard import views as dashboard




app_name = 'dashboard'
urlpatterns = [
  path('dashboard/', dashboard.dashboard_page, name="dashboard_page"),




  path('addemployee/', dashboard.add_employee, name="add_employee"),
  path('employees/', dashboard.list_employee, name="list_employee"),
  path('employee/update/<int:id>', dashboard.update_employee, name="update_employee"),
  path('employee/delete/<int:id>', dashboard.delete_employee, name="delete_employee"),




  path('medicine/', dashboard.medicine_list_admin, name="medicine_list_admin"),
  path('medicine/delete/<int:id>', dashboard.delete_medicine, name="delete_medicine"),
  path('medicine/update/<int:id>', dashboard.update_medicine, name="update_medicine"),
  path('medicine/add/', dashboard.add_medicine, name="add_medicine"),




  path('faq/', dashboard.faq_list, name="faq_list"),
  path('faq/add/', dashboard.faq_add, name="faq_add"),




  path('upload/prescription/', dashboard.upload_prescription, name="upload_prescription"),
  path('prescription/<int:id>/update', dashboard.update_prescription, name="update_prescription"),
  path('prescription/', dashboard.presciption_list_admin, name="presciption_list_admin"),
 
  path('notification/add/', dashboard.add_notification, name="add_notification"),
 
  path('sales/', dashboard.sales_list, name="sales_list"),
  path('sales/add/', dashboard.add_sales, name="add_sales"),
  path('sales/<int:id>/update/', dashboard.update_sales, name="update_sales"),
 
  path("bills/", dashboard.list_bill, name="list_bill"),
  path("bills/add/", dashboard.generate_bill, name="generate_bill"),
  path("bills/update/<int:id>/", dashboard.update_bill, name="update_bill"),


  path("billitem/<int:bill_id>/", dashboard.bill_item_list, name="bill_item_list"),
  path("billitem/<int:bill_id>/add/", dashboard.generate_bill_items, name="generate_bill_items"),
  path("billitem/<int:bill_id>/delete/<int:item_id>/", dashboard.delete_bill_item, name="delete_bill_item"),


  path("cbills/<int:app_id>", dashboard.customer_bills, name="customer_bills"),
 
  path("search/", dashboard.search_by_email, name="search_by_email"),
]

pharmaLink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


admin.site.site_header = "pharmaLink"
admin.site.index_title = "pharmaLink dashboard"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('dashboard.urls')),


    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User
from dashboard.models import *








class EmployeeRegisterForm(UserCreationForm):
 class Meta:
     model = User
     fields = ('email', 'first_name', 'last_name', 'address', 'phone', 'dob', 'password1', 'password2')








class EmployeeUpdateForm(forms.ModelForm): 
 class Meta:
     model = User
     fields = ('email', 'first_name', 'last_name', 'address', 'phone', 'dob')








class StocksUpdateForm(forms.ModelForm):
  manufacture_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'})) 
  expiry_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'})) 
  class Meta:
     model = Stocks
     fields = ('name', 'generic_name', 'dosage_strength', 'dose_form', 'manufacture_name', 'manufacture_date', 'stock', 'batch', 'expiry_date','extra_detail')








class FaqAddForm(forms.ModelForm):
 class Meta:
     model = FAQ
     fields = ('question', 'answer')
  
class DoctorsPrescriptionAddForm(forms.ModelForm):
 class Meta:
     model = DoctorsPrescription
     fields = ('prescription', 'customer_notes')
  
class DoctorsPrescriptioncustomerUpdateForm(forms.ModelForm):
 class Meta:
     model = DoctorsPrescription
     fields = ('prescription', 'customer_notes')




class DoctorsPrescriptionemployeeUpdateForm(forms.ModelForm):
 class Meta:
     model = DoctorsPrescription
     fields = ('employee_notes','status')
   
   
class AddNotification(forms.ModelForm):
 class Meta:
     model = Notification
     fields = ('specific_user','notification')
    
class SalesForm(forms.ModelForm):
  manufacture_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'})) 
  expiry_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'})) 
  class Meta:
     model = Sales
     fields = ('name', 'generic_name', 'dosage_strength', 'dose_form', 'manufacture_name', 'manufacture_date', 'qty', 'batch', 'expiry_date','price','extra_detail')








class GenerateBillForm(forms.ModelForm):
   class Meta:
       model = Bills
       fields = ('customer','prescription', 'bill_no', 'sub_total', 'discount', 'net_amount', 'paid_status')


       labels = {
           "customer" : "customer"
       }
      


class AddBillItemForm(forms.ModelForm):
   class Meta:
       model = BillsItems
       fields = ('description', 'qty', 'amount')

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from dashboard.models import Stocks, FAQ, DoctorsPrescription
from dashboard.forms import *
from django.contrib import messages
from accounts.models import User
from django.utils import timezone
from datetime import date


# Create your views here.
@login_required(login_url='/')
def dashboard_page(request):
 medicine = Stocks.objects.all()
 today = date.today() 
 medicine_expire = Stocks.objects.filter(expiry_date__lt=today)
 users_count = User.objects.filter(is_customer=True).count()
 medicine_count = Stocks.objects.all().count()
 expired_medicine_count = Stocks.objects.filter(expiry_date__lt=timezone.now()).count()
 prescription = DoctorsPrescription.objects.filter(user=request.user).order_by('-id')




 jan_medicine = Stocks.objects.filter(created_date__month=1).count()
 feb_medicine = Stocks.objects.filter(created_date__month=2).count()
 mar_medicine = Stocks.objects.filter(created_date__month=3).count()
 apr_medicine = Stocks.objects.filter(created_date__month=4).count()
 may_medicine = Stocks.objects.filter(created_date__month=5).count()
 june_medicine = Stocks.objects.filter(created_date__month=6).count()
 july_medicine = Stocks.objects.filter(created_date__month=7).count()
 aug_medicine = Stocks.objects.filter(created_date__month=8).count()
 sep_medicine = Stocks.objects.filter(created_date__month=9).count()
 oct_medicine = Stocks.objects.filter(created_date__month=10).count()
 nov_medicine = Stocks.objects.filter(created_date__month=11).count()
 dec_medicine = Stocks.objects.filter(created_date__month=12).count()
 context = {
     'medicine' : medicine,
     'medicine_expire' : medicine_expire,
     'users_count' : users_count,
     'medicine_count' : medicine_count,
     'expired_medicine_count' : expired_medicine_count,
     'jan_medicine' : jan_medicine,
     'feb_medicine' : feb_medicine,
     'mar_medicine' : mar_medicine,
     'apr_medicine' : apr_medicine,
     'may_medicine' : may_medicine,
     'june_medicine' : june_medicine,
     'july_medicine' : july_medicine,
     'aug_medicine' : aug_medicine,
     'sep_medicine' : sep_medicine,
     'oct_medicine' : oct_medicine,
     'nov_medicine' : nov_medicine,
     'dec_medicine' : dec_medicine,
     'prescription' : prescription,
  
 }
 return render(request,'dashboard/dashboard.html', context)








@login_required(login_url='/')
def add_employee(request):
 if request.method == "POST":
     form = EmployeeRegisterForm(request.POST)
     if form.is_valid():
         user = form.save(commit=False)
         user.is_active = True
         user.is_employee = True
         user.username = form.cleaned_data.get('email')
         user.save()
         messages.success(request, "Successfully Added Employee")
         return redirect("dashboard:list_employee")
 else:
     form = EmployeeRegisterForm()
 return render(request, 'dashboard/employee/add.html', {'form': form})








@login_required(login_url='/')
def list_employee(request):
 employee = User.objects.filter(is_employee=True)
 context = {
     'employees' : employee
 }
 return render(request, "dashboard/employee/list.html", context)








@login_required(login_url='/')
def delete_employee(request, id):
 employee = User.objects.filter(is_employee=True, id=id).first()
 employee.delete()
 return redirect("dashboard:list_employee")
















@login_required(login_url='/')
def update_employee(request, id):








 employee = User.objects.filter(is_employee=True, id=id).first()
 if request.method == "POST":
     form = EmployeeUpdateForm(request.POST, instance=employee)
     if form.is_valid():
         user = form.save(commit=False)
         user.is_active = True
         user.is_employee = True
         user.username = form.cleaned_data.get('email')
         user.save()
         messages.success(request, "Successfully Updated Employee")
         return redirect("dashboard:list_employee")
 else:
     form = EmployeeUpdateForm(instance=employee)
 return render(request, "dashboard/employee/update.html", {'form': form})
















@login_required(login_url='/')
def medicine_list_admin(request):
 medicine = Stocks.objects.all()
 return render(request, "dashboard/medicine/list.html", {"medicine" : medicine})








@login_required(login_url='/')
def delete_medicine(request, id):
 medicine = Stocks.objects.filter(id=id).first()
 medicine.delete()
 return redirect("dashboard:medicine_list_admin")
















@login_required(login_url='/')
def update_medicine(request, id):








 medicine = Stocks.objects.filter(id=id).first()
 if request.method == "POST":
     form = StocksUpdateForm(request.POST, instance=medicine)
     if form.is_valid():
         medicine = form.save(commit=False)
         medicine.save()
         messages.success(request, "Successfully Updated Medicine")
         return redirect("dashboard:medicine_list_admin")
 else:
     form = StocksUpdateForm(instance=medicine)
 return render(request, "dashboard/medicine/update.html", {'form': form})








@login_required(login_url='/')
def add_medicine(request):
 if request.method == "POST":
     form = StocksUpdateForm(request.POST)
     if form.is_valid():
         medicine = form.save(commit=False)
         medicine.save()
         messages.success(request, "Successfully Added Medicine")
         return redirect("dashboard:medicine_list_admin")
 else:
     form = StocksUpdateForm()
 return render(request, 'dashboard/medicine/add.html', {'form': form})








@login_required(login_url='/')
def faq_list(request):
 faq = FAQ.objects.all()
 return render(request, "dashboard/faq/list.html", {'faq': faq})








@login_required(login_url='/')
def faq_add(request):
 if request.method == "POST":
     form = FaqAddForm(request.POST)
     if form.is_valid():
         form.save()
         messages.success(request, "Successfully Added FAQ")
         return redirect("dashboard:faq_list")
 else:
     form = FaqAddForm()
 return render(request, 'dashboard/faq/add.html', {'form': form})
















@login_required(login_url='/')
def upload_prescription(request):
 if request.method == "POST":
     form = DoctorsPrescriptionAddForm(request.POST, request.FILES)
     if form.is_valid():
         prescription = form.save(commit=False)
         prescription.user = request.user
         prescription.save()
         Notification.objects.create(notification="New pescription has been posted", created_by=request.user, specific_user=User.objects.filter(is_employee=True).first())
         messages.success(request, "Successfully Uploaded")
         return redirect("dashboard:dashboard_page")
 else:
     form = DoctorsPrescriptionAddForm()
 return render(request, 'dashboard/prescription/add.html', {'form': form})
















@login_required(login_url='/')
def update_prescription(request, id):
 presciption = DoctorsPrescription.objects.filter(id=id).first()
 if request.method == "POST":
     if request.user.is_customer:
         form = DoctorsPrescriptioncustomerUpdateForm(request.POST, instance=presciption)
     if request.user.is_employee:
         form = DoctorsPrescriptionemployeeUpdateForm(request.POST, instance=presciption)
     if form.is_valid():
         pre = form.save(commit=False)
         pre.user = request.user
         pre.save()
         messages.success(request, "Successfully Updated presciption")
         return redirect("dashboard:dashboard_page")
 else:
     if request.user.is_customer:
         form = DoctorsPrescriptioncustomerUpdateForm(instance=presciption)
     if request.user.is_employee:
         form = DoctorsPrescriptionemployeeUpdateForm(instance=presciption)
 return render(request, "dashboard/prescription/update.html", {'form': form})








@login_required(login_url='/')
def presciption_list_admin(request):
 prescription = DoctorsPrescription.objects.all().order_by('-id')
 return render(request, "dashboard/prescription/list.html", {'prescription': prescription})












@login_required(login_url='/')
def add_notification(request):
  if request.method == "POST":
      form = AddNotification(request.POST)
      if form.is_valid():
          notif = form.save(commit=False)
          notif.created_by = request.user
          notif.save()
          messages.success(request, "Successfully Added Notification")
          print('-----------------------------------')
          return redirect("dashboard:dashboard_page")
  else:
      form = AddNotification()
  return render(request, 'dashboard/notification/add.html', {'form': form})
@login_required(login_url='/')
def sales_list(request):
 sales = Sales.objects.all()
 return render(request, "dashboard/sales/list.html", {"sales" : sales})


# @login_required(login_url='/')
# def delete_sales(request, id):
#   medicine = Sales.objects.filter(id=id).first()
#   medicine.delete()
#   return redirect("dashboard:sales_list")




@login_required(login_url='/')
def update_sales(request, id):


 medicine = Sales.objects.filter(id=id).first()
 if request.method == "POST":
     form = SalesForm(request.POST, instance=medicine)
     if form.is_valid():
         medicine = form.save(commit=False)
         medicine.save()
         messages.success(request, "Successfully Updated sales")
         return redirect("dashboard:sales_list")
 else:
     form = SalesForm(instance=medicine)
 return render(request, "dashboard/sales/update.html", {'form': form})


@login_required(login_url='/')
def add_sales(request):
 if request.method == "POST":
     form = SalesForm(request.POST)
     if form.is_valid():
         medicine = form.save(commit=False)
         medicine.save()
         messages.success(request, "Successfully Added sales")
         return redirect("dashboard:sales_list")
 else:
     form = SalesForm()
 return render(request, 'dashboard/sales/add.html', {'form': form})


@login_required(login_url='/')
def generate_bill(request):
   if request.method == 'POST':

templates/dashboard/bills/add.html
{% extends "partials/layout.html" %}  


{% block navbar %}
{% include "partials/navbar.html" %}
{% endblock navbar %}
      
    
{% block sidebar %}
{% include "partials/sidebar.html" %}
{% endblock sidebar %}
          
              
{% block content %}
{% load crispy_forms_tags %}
{% if request.user.is_superuser or request.user.is_employee %}
<h1 class="m-2 text-mute text-center">Generate Bill</h1>
<div class="container">
   <form action="" method="post">
       {% csrf_token %}
       {{form|crispy}}
       <button class = "btn btn-info">Generate Bill</button>
   </form>
</div>
{% endif %}
{% endblock content %} 
{% block script %}
{% include "partials/script.html" %}
{% endblock script %}

templates/dashboard/bills/customer_bill.html
<!doctype html>
<html lang="en">


<head>
   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
       integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


   <title>{{cbill.customer.first_name}} {{cbill.customer.last_name}}</title>
   <style type="text/css" media="print">
       .dontprint
       { display: none; }
   </style>
</head>


<body>
   {% if cbill %}
   <div class="container  mt-5 mb-5 " style="width: 80%; font-size: 11px;">
       <h1 class="text-center">
           PHARMALINK
       </h1>
       <table class="table table-bordered mt-4" style=" border: px solid black;">
           <thead>
               <!-- first  start-->
               <tr>
                   <th scope="col" colspan="10" class="text-center"> INVOICE</th>
               </tr>
               <!-- first end -->
           </thead>
           <tbody>
               <tr>
                   <th scope="row" colspan="10">
                       M/S: {{cbill.customer.first_name}} {{cbill.customer.last_name}}<br>
                       Address: {{cbill.customer.address}}<br>
                       Phone No: {{cbill.customer.phone}} <br>
                       Date: {{cbill.created_date}} <br>
                   </th>
               </tr>
               <tr>
                   <th style="width:5%;">S.N</th>
                   <th style="width:60%;">Description</th>
                   <th>Quantity</th>
                   <th>Amount</th>
               </tr>
               {% for i in cbill.billitem.all %}
               <tr>
                   <th colspan="1">{{forloop.counter}}</th>
                   <th colspan="1">{{i.description}}</th>
                   <th colspan="1">{{i.qty}}</th>
                   <th colspan="1">{{i.amount}}/-</th>
               {% endfor %}
               </tr>
                   <th colspan="2" rowspan="2">
                       {% comment %} <b>Amount:</b> one thousand one hundered twentry /- {% endcomment %}
                   </th>
                   <th colspan="2" rowspan="2">
                       <b>Total Amount:</b> {{cbill.net_amount}}/-
                   </th>
               </tr>
           </tbody>
       </table>
   </div>
   <div>
       <button class="btn btn-info dontprint" style="margin-left: 45%;" onclick="window.print()">Print Invoice</button>
   </div>
   {% else %}
   <p class="text-center" style="margin-top: 20%; font-size: 29px;">!!! Bill has not been generated !!!</p>
   {% endif %}


   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
       integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
       crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
       integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
       crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
       integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
       crossorigin="anonymous"></script>
</body>


</html>

templates/dashboard/bills/list.html
{% extends "partials/layout.html" %}  


{% block navbar %}
{% include "partials/navbar.html" %}
{% endblock navbar %}
      
    
{% block sidebar %}
{% include "partials/sidebar.html" %}
{% endblock sidebar %}
          
              
{% block content %}
{% load crispy_forms_tags %}
{% if request.user.is_superuser or request.user.is_employee %}
<h1 class="m-2 text-mute text-center">Bills List</h1>
<table class="table">
   <thead>
     <tr>
       <th scope="col">S.N</th>
       <th scope="col">Patient Name</th>
       <th scope="col">Bill No</th>
       <th scope="col">Address</th>
       <th scope="col">Contact</th>
       <th scope="col">Paid Status</th>
       <th scope="col">Actions</th>
     </tr>
   </thead>
   <tbody>
       {% for bill in bill  %}
     <tr>
       <th scope="row">{{forloop.counter}}</th>
       <td>{{bill.customer.first_name}} {{bill.customer.last_name}} </td>
       <td>{{bill.bill_no}}</td>
       <td>{{bill.customer.address}}</td>
       <td>{{bill.customer.phone}}</td>
       <td>
           {% if bill.paid_status == True %}
           <p class="badge badge-success">Paid</p>
           {% else %}
           <p class="badge badge-warning">UnPaid</p>
           {% endif %}
       </td>
       <td><a href="{% url "dashboard:update_bill" bill.id %}" class="btn btn-primary">Edit</a></td>
     </tr>
     {% endfor %}
   </tbody>
 </table>
{% endif %}
{% endblock content %} 
{% block script %}
{% include "partials/script.html" %}
{% endblock script %}

templates/dashboard/bills/update.html
{% extends "partials/layout.html" %}  


{% block navbar %}
{% include "partials/navbar.html" %}
{% endblock navbar %}
      
    
{% block sidebar %}
{% include "partials/sidebar.html" %}
{% endblock sidebar %}
          
              
{% block content %}
{% load crispy_forms_tags %}
{% if request.user.is_superuser or request.user.is_employee %}
<h1 class="m-2 text-mute text-center">Update Bill</h1>
<div class="container">
   <form action="" method="post">
       {% csrf_token %}
       {{form|crispy}}
       <div class="row">
           <button class = "btn btn-info">Update Bill</button>
          
           <a href="{% url "dashboard:generate_bill_items" bill_id=form.instance.id %}" class = "btn btn-info ml-2"> Add Bill Item</a>
           <a href="{% url "dashboard:bill_item_list" bill_id=form.instance.id %}" class = "btn btn-info ml-2"> view Bill Item</a>
       </div>
   </form>
</div>
{% endif %}
{% endblock content %} 
{% block script %}
{% include "partials/script.html" %}
{% endblock script %}